server:
  host: "localhost"
  port: 8080
  sockets:
    admin:
      port: 8090

client.default:
  uri: "http://localhost:8080"

metrics:
  web-context: "metrics"
  routing: admin

db.pokemon:
  source: jdbc
  connection:
    url: "jdbc:h2:tcp://localhost:9092/test"
    username: sa
    password:
  statements:
    create-table: "CREATE TABLE pokemons (name VARCHAR(64) NOT NULL PRIMARY KEY, type VARCHAR(32))"
    insert: "INSERT INTO pokemons VALUES(:name, :type)"
    insert-indexed: "INSERT INTO pokemons VALUES(?, ?)"
    select-one: "SELECT * FROM pokemons WHERE name = ?"
    select-all: "SELECT * FROM pokemons"


security:
  providers:
    - http-basic-auth:
        users:
          - login: "john"
            password: "password"
            roles: ["admin"]
          - login: "jack"
            password: "password"
            roles: ["user"]
          - login: "jill"
            password: "password"
    - abac:
  web-server:
    defaults:
      authenticate: true
    paths:
      - path: "/service"
        methods: ["get"]
        roles-allowed: "user"
